# Generated by Django 3.1.4 on 2020-12-21 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201221_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
